version: '3'

networks:
  python-app:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '5000:5000'
    networks:
      - python-app
  redis:
    image: redis:latest
    restart: always
    networks:
      - python-app